### ISSUE TITLE
How to handle upstream kernel updates

### ISSUE THREAD

**Issue by hanthor** [centos-workstation/main#4]
What do we do when centos updates but the upstream image doesn't and the kernel get out of sync? It leads to an error like `Failed to find kernel in /usr/lib/modules, /usr/lib/ostree-boot or /boot`

**Comment by cgwalters** [comment]
https://gitlab.com/redhat/centos-stream/containers/bootc/-/issues/1170

**Comment by hanthor** [comment]
Thanks, we should probably keep the kernel cleanup in the build just in case, I'm assuming that would be best practice

**Comment by hanthor** [comment]
![image](https://github.com/user-attachments/assets/a59118ea-771a-467a-9f4b-06d161af52fd)

running:

`dnf remove -y $(dnf repoquery --installonly --latest-limit 1 -q)`


is necessary to ensure that there is only one kernel present on the image and to get bootc linting to pass. but it seems running it break the image the above error

**Comment by hanthor** [comment]
```
STEP 4/5: RUN bootc container lint || exit 0 
ERROR Linting: Found multiple subdirectories in usr/lib/modules
--> 9fbee91fbd16
```

**Comment by tulilirockz** [comment]
@hanthor is this still happening for you? i believe it should be fine now with the latest builds

**Comment by hanthor** [comment]
I think this is better but is Upstream updating?
